spring:
  session:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username : root
#    password: 1234
    url: jdbc:h2:file:/hoop/data/test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  social:
    kakao:
      client_id: c821057d14c2438354f518b12064a435
      redirect: http://localhost:8080/auth/kakao?
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: c:\\temp\\upload

hoop:
  uri: http://localhost:8080
  jwt-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="
  source-path: /hoop

logging:
  logback:
    rolling policy:
      max-history: 30
      file-name-pattern: "/hoop/logs/abc.%d{yyyy-MM-dd}.%i"
  pattern:
      file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
      name: /hoop/logs/abc.log
  level:
      root: INFO
      org.hibernate.SQL: ERROR
      org.springframework.security: debug
      org.springframework.web: debug